### ISSUE TITLE
Duplicate pct key handeling

### ISSUE THREAD

**Issue by 09williamsad** [Wildenhaus/IndexV2#20]
OS: Windows 11 24H2
IndexV2 version: v0.4.0.1
Game: Space Marine 2 4.0

If the 4K texture pack DLC is installed and IndexV2 tries to load Space Marine 2, then the below error occurs:
"An item with the same key has already been added. Key: acid_bomb_expl_material.pct

System.ArgumentException: An item with the same key has already been added. Key: acid_bomb_expl_material.pct
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Index.Domain.Assets.AssetReferenceCollection`1.AddReference(IAssetReference assetReference)
   at Index.Domain.Assets.AssetManager.InitializeFromFileSystem(IFileSystem fileSystem)
   at Index.App.ViewModels.EditorLoadingViewModel.InitializeAssetManager()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Index.App.ViewModels.EditorLoadingViewModel.RunTask(String status, Action action)
   at Index.App.ViewModels.EditorLoadingViewModel.Initialize()"

This can be worked around by deleting the non-4K texture default_pct_xx.pak and default_resources.pak files.
However this prevents anything other than the 4K textures being loaded, until the 4K paks are deleted.

**Comment by Wildenhaus** [comment]
I have that crash resolved. The issue now is that the 4k textures have some weird stuff going on with their format:

![image](https://github.com/user-attachments/assets/8f92c2a4-b979-46be-bf2e-ec27e67df144)

Which doesn't conform to the model UVs:
![image](https://github.com/user-attachments/assets/867b4622-fc93-4ddb-8093-81901545752f)

**Comment by Wildenhaus** [comment]
Fixed with [v0.4.0.2](https://github.com/Wildenhaus/IndexV2/releases/tag/v0.4.0.2)

Feel free to re-open this ticket if there are still issues.
