### ISSUE TITLE
Assertion Failed: fioZIP_CACHE_FILE::Entry did not start with a 5

### ISSUE THREAD

**Issue by Kmdl14** [Wildenhaus/IndexV2#24]
I when I click launch I get the following message:

LibSaber.Assertions+AssertionFailedException: Assertion Failed: fioZIP_CACHE_FILE::Entry did not start with a 5
   at LibSaber.Assertions.ThrowAssertionFailedException(String reason)
   at LibSaber.Assertions.ASSERT(Boolean expression, String reason)
   at LibSaber.SpaceMarine2.Serialization.Resources.fioZIP_CACHE_FILESerializer.Deserialize(NativeReader reader, ISerializationContext context)
   at LibSaber.SpaceMarine2.Serialization.Serializer`1.Deserialize(NativeReader reader, ISerializationContext context)
   at LibSaber.SpaceMarine2.Structures.Resources.fioZIP_FILE.ReadCacheFile(String filePath)
   at LibSaber.SpaceMarine2.Structures.Resources.fioZIP_FILE.Open(String filePath)
   at Index.Profiles.SpaceMarine2.FileSystem.SM2PckDevice..ctor(String basePath, String filePath)
   at Index.Profiles.SpaceMarine2.FileSystem.SM2FileSystemLoader.<OnLoadDevices>b__0_0(String path)
   at Index.Domain.FileSystem.FileSystemLoaderBase.LoadDevice(String path, Func`2 deviceFactory)
   at Index.Domain.FileSystem.FileSystemLoaderBase.LoadFilesWithExtension(String extension, Func`2 deviceFactory, IEnumerable`1 excludedFileNames)
   at Index.Profiles.SpaceMarine2.FileSystem.SM2FileSystemLoader.OnLoadDevices()
   at Index.Domain.FileSystem.FileSystemLoaderBase.LoadDevices()
   at Index.Domain.FileSystem.FileSystem.LoadDevices(IFileSystemLoader deviceLoader)
   at Index.App.ViewModels.EditorLoadingViewModel.InitializeFileSystem()
   at Index.App.ViewModels.EditorLoadingViewModel.RunTask(String status, Func`1 taskFactory)
   at Index.App.ViewModels.EditorLoadingViewModel.Initialize()

I don't know if I'm doing something wrong, or if it's just my game

**Comment by Wildenhaus** [comment]
Duplicate of #15 
[you are using an outdated version](https://github.com/Wildenhaus/IndexV2/releases/)
