### ISSUE TITLE
Assertion Failed: Unknown property for TextureShader: z_write_force_off

### ISSUE THREAD

**Issue by Nihren** [Wildenhaus/IndexV2#3]
When I try to load shared/needler_h from Halo 2 Anniversary in v0.3.0.1 I get the following error prompt:

An unhandled error has occurred.

Assertion Failed: Unknown property for TextureShader: z_write_force_off

LibSaber.Assertions+AssertionFailedException: Assertion Failed: Unknown property for TextureShader: z_write_force_off
   at LibSaber.Assertions.ThrowAssertionFailedException(String reasonFormat, Object[] formatArgs)
   at LibSaber.Halo2A.Serialization.Scripting.ScriptingSerializer`1.GetProperty(String propertyName)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ReadProperty(StringReader reader, T obj)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.LibSaber.Halo2A.Serialization.Scripting.ITextScriptingSerializer.Deserialize(StringReader reader)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseValue(StringReader reader, Type type, String value)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseDictionary(StringReader reader, Type dictionaryType)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseValue(StringReader reader, Type type, String value)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ReadProperty(StringReader reader, T obj)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.LibSaber.Halo2A.Serialization.Scripting.ITextScriptingSerializer.Deserialize(StringReader reader)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseValue(StringReader reader, Type type, String value)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseDictionary(StringReader reader, Type dictionaryType)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ParseValue(StringReader reader, Type type, String value)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.ReadProperty(StringReader reader, T obj)
   at LibSaber.Halo2A.Serialization.Scripting.TextScriptingSerializer`1.OnDeserialize(Stream stream, T obj)
   at Index.Profiles.Halo2A.Jobs.LoadGeometryTexturesJob.GatherAdditionalTextures()
   at Index.Profiles.Halo2A.Jobs.LoadGeometryTexturesJob.OnExecuting()
   at Index.Jobs.JobBase.Execute()

![image](https://github.com/Wildenhaus/IndexV2/assets/155014059/06a77a4d-3cce-45bd-a14b-e7bd35134c00)

This is preventing me from loading the model in viewer and thus preventing export of the mesh and textures. I used the older version of Index to get the model, but that one was unable to export the textures still.

**Comment by Wildenhaus** [comment]
This has been fixed in [0.3.0.2.](https://github.com/Wildenhaus/IndexV2/releases/tag/v0.3.0.2)
